# Generated by Django 3.2.7 on 2022-09-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piza', '0003_remove_customers_ingridiend_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='ingridiend_id',
        ),
        migrations.AddField(
            model_name='products',
            name='Ingredients',
            field=models.CharField(default=1, max_length=300, verbose_name='Ингридиенд'),
            preserve_default=False,
        ),
    ]
