# Generated by Django 3.2.7 on 2022-09-15 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piza', '0010_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users',
        ),
        migrations.AlterField(
            model_name='customers',
            name='comment',
            field=models.CharField(max_length=100, null=True, verbose_name='Коментарии'),
        ),
    ]
