# Generated by Django 3.2.7 on 2022-09-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piza', '0019_auto_20220915_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(max_length=5, verbose_name='Цены'),
        ),
    ]
