# Generated by Django 3.2.7 on 2022-09-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piza', '0021_alter_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_report',
            name='product_id',
            field=models.IntegerField(verbose_name='ID продукт'),
        ),
    ]
