# Generated by Django 3.2.7 on 2022-09-15 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piza', '0023_testtable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestTable',
        ),
    ]
