# Generated by Django 3.2.7 on 2022-09-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piza', '0028_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='adress',
            field=models.CharField(max_length=100, null=True, verbose_name='Адрес доставки'),
        ),
    ]
