# Generated by Django 3.2 on 2022-10-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piza', '0036_auto_20220923_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12, verbose_name='Номер телефон')),
                ('name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('adress', models.CharField(max_length=100, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Контактная информация',
                'verbose_name_plural': 'Контактная информация',
                'ordering': ['id'],
            },
        ),
    ]
