# Generated by Django 3.2 on 2022-11-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piza', '0049_auto_20221118_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст')),
                ('stime', models.DateTimeField(max_length=15, verbose_name='Дата конец')),
                ('etime', models.DateTimeField(max_length=15, verbose_name='Дата конец')),
            ],
            options={
                'verbose_name': 'Текст Меню',
                'verbose_name_plural': 'Текст Меню',
            },
        ),
    ]
