# Generated by Django 3.2 on 2022-11-22 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piza', '0051_auto_20221122_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_info',
            old_name='adres',
            new_name='adress',
        ),
        migrations.RenameField(
            model_name='contact_info',
            old_name='fio',
            new_name='name',
        ),
    ]
