# Generated by Django 3.2 on 2022-11-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piza', '0057_auto_20221130_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_phone', models.CharField(max_length=12, null=True, verbose_name='Телефон курьера')),
                ('order_id', models.CharField(max_length=100, null=True, verbose_name='Номер заказа')),
                ('comment', models.CharField(max_length=100, null=True, verbose_name='Коментарии')),
                ('cre_date', models.DateTimeField(auto_now_add=True, max_length=15, verbose_name='Время создание заказа')),
                ('status', models.IntegerField(choices=[(0, 'Карзина'), (1, 'Самовоз'), (2, 'В процессе'), (3, 'На доставке'), (4, 'Доставлено'), (5, 'Отказ')], verbose_name='Статус')),
            ],
        ),
    ]
