# Generated by Django 3.2 on 2022-11-30 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piza', '0060_auto_20221130_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryinfo',
            name='delivery_etime',
        ),
    ]
