# Generated by Django 3.2 on 2022-10-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenCredentianls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.CharField(max_length=15)),
                ('subs_id', models.IntegerField(blank=True, null=True)),
                ('otp_value', models.IntegerField(blank=True, null=True)),
                ('txn_value', models.IntegerField(default=339763)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('device_model', models.CharField(max_length=200)),
                ('device_os', models.CharField(max_length=200)),
                ('device_ip', models.CharField(max_length=50)),
                ('device_token', models.CharField(max_length=200)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuthHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('otp', models.CharField(max_length=5)),
                ('token', models.CharField(max_length=256)),
                ('verified', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('device_model', models.CharField(blank=True, max_length=50, null=True)),
                ('device_os', models.CharField(blank=True, max_length=20, null=True)),
                ('device_ip', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'ordering': ['create_date'],
            },
        ),
    ]
