# Generated by Django 3.2.7 on 2022-09-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название продукта')),
                ('price', models.IntegerField(verbose_name='Цены')),
                ('category', models.IntegerField(choices=[(1, 'Пицца'), (2, 'Бургер'), (3, 'Стрипсы'), (4, 'Напитки'), (5, 'Прочи')], verbose_name='Категория')),
                ('image', models.CharField(max_length=250, verbose_name='Фото')),
                ('ingridiend_id', models.IntegerField(verbose_name='Ингридиенд')),
                ('status', models.IntegerField(choices=[(1, 'Активна'), (2, 'Отключена')], verbose_name='Статус')),
            ],
        ),
    ]
