# Generated by Django 3.2.7 on 2022-09-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piza', '0004_auto_20220914_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='device_token',
            field=models.CharField(default=1111, max_length=250, verbose_name='ФИО клиент'),
            preserve_default=False,
        ),
    ]
