# Generated by Django 3.2.7 on 2022-09-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piza', '0005_customers_device_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customers',
            options={'ordering': ['-id'], 'verbose_name': 'Клиенты', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Продукты', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AddField(
            model_name='customers',
            name='comment',
            field=models.CharField(default=1, max_length=100, verbose_name='Коментарии'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customers',
            name='device_token',
            field=models.CharField(max_length=250, verbose_name='Устройства'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
