# Generated by Django 3.2.7 on 2022-09-15 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piza', '0007_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.IntegerField(verbose_name='Уникальный номер пользователя'),
        ),
    ]
