# Generated by Django 3.2.7 on 2022-09-15 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piza', '0008_alter_users_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users',
        ),
    ]
