# Generated by Django 3.2.7 on 2022-09-15 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piza', '0009_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='Уникальный номер пользователя')),
                ('user_name', models.CharField(max_length=50, verbose_name='ФИО пользователя')),
            ],
        ),
    ]
