# Generated by Django 3.2.7 on 2022-09-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piza', '0011_auto_20220915_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100, verbose_name='ФИО клиент')),
                ('status', models.IntegerField(choices=[(1, 'Активна'), (2, 'Отключена')], verbose_name='Статус')),
            ],
        ),
    ]
