# Generated by Django 3.2.7 on 2022-09-15 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piza', '0012_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='sales_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12, verbose_name='Номер телефон')),
                ('product_id', models.IntegerField(max_length=4, verbose_name='ID продукт')),
                ('product_price', models.IntegerField(max_length=4, verbose_name='Цены')),
                ('date', models.DateTimeField(max_length=15, verbose_name='Время продаж')),
                ('delivery_address', models.CharField(max_length=200, verbose_name='Адресс доставки')),
                ('comment', models.CharField(max_length=100, null=True, verbose_name='Коментарии')),
                ('status', models.IntegerField(choices=[(1, 'Продан'), (2, 'Отменен')], verbose_name='Статус')),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Категории', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_name',
            field=models.CharField(max_length=100, verbose_name='Категория'),
        ),
    ]
