# Generated by Django 3.2.7 on 2022-09-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piza', '0013_auto_20220915_1027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales_report',
            options={'ordering': ['-date'], 'verbose_name': 'Отчет по продаж', 'verbose_name_plural': 'Отчет по продаж'},
        ),
        migrations.AddField(
            model_name='category',
            name='comment',
            field=models.CharField(max_length=100, null=True, verbose_name='Коментарии'),
        ),
    ]
