# Generated by Django 3.2.7 on 2022-09-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piza', '0014_auto_20220915_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=1, upload_to='photos/%Y/%m/%d', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
