# Generated by Django 3.2.7 on 2022-09-15 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piza', '0016_alter_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
