# Generated by Django 3.2.7 on 2022-09-15 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piza', '0017_remove_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='icon/%Y/%m/%d', verbose_name='Значок'),
        ),
    ]
