# Generated by Django 3.2.7 on 2022-09-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piza', '0018_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='category_icon/%Y/%m/%d', verbose_name='Значок'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(max_length=100, verbose_name='Цены'),
        ),
    ]
