# Generated by Django 3.2.7 on 2022-09-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piza', '0022_alter_sales_report_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'test_table',
                'managed': False,
            },
        ),
    ]
