# Generated by Django 3.2.7 on 2022-09-21 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piza', '0025_testtable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testtable',
            options={'managed': False, 'verbose_name': 'Тестовая таблица', 'verbose_name_plural': 'Тестовая таблица'},
        ),
        migrations.RemoveField(
            model_name='sales_report',
            name='product_id',
        ),
        migrations.AddField(
            model_name='category',
            name='position',
            field=models.IntegerField(blank=True, null=True, verbose_name='Позиция'),
        ),
        migrations.AddField(
            model_name='sales_report',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='piza.products', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='sales_report',
            name='product_price',
            field=models.IntegerField(verbose_name='Сумма'),
        ),
    ]
