# Generated by Django 3.2.7 on 2022-09-21 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piza', '0027_products_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12, verbose_name='Номер телефон')),
                ('date', models.DateTimeField(max_length=15, verbose_name='Время создание заказа')),
                ('time_delivery', models.DateTimeField(max_length=15, verbose_name='Время доставки')),
                ('status', models.IntegerField(choices=[(1, 'В процессе'), (2, 'На доставке'), (3, 'Отказ')], verbose_name='Статус')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='piza.products', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Заказы',
                'verbose_name_plural': 'Заказы',
                'ordering': ['date'],
            },
        ),
    ]
