# Generated by Django 3.2.7 on 2022-09-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piza', '0029_orders_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='comment',
            field=models.CharField(max_length=100, null=True, verbose_name='Коментарии'),
        ),
        migrations.AddField(
            model_name='orders',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(auto_now_add=True, max_length=15, verbose_name='Время создание заказа'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.IntegerField(choices=[(1, 'Самовоз'), (2, 'В процессе'), (3, 'На доставке'), (4, 'Отказ')], verbose_name='Статус'),
        ),
    ]
