# Generated by Django 3.2 on 2022-09-23 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piza', '0035_auto_20220921_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ProductItem', to='piza.products', to_field='name'),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='volume_name',
            field=models.CharField(max_length=5, verbose_name='Объем/размер'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название продукта'),
        ),
    ]
