# Generated by Django 3.2 on 2022-10-17 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piza', '0037_contact_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_time', models.DateTimeField(verbose_name='Время доставки')),
                ('adress', models.CharField(max_length=100, null=True, verbose_name='Адрес доставки')),
                ('comment', models.CharField(max_length=100, null=True, verbose_name='Коментарии')),
                ('cre_date', models.DateTimeField(auto_now_add=True, max_length=15, verbose_name='Время создание заказа')),
                ('phone', models.CharField(max_length=12, null=True, verbose_name='Телефон')),
                ('date', models.DateTimeField(auto_now_add=True, max_length=15, verbose_name='Время создание заказа')),
                ('time_delivery', models.DateTimeField(max_length=15, verbose_name='Время доставки')),
                ('status', models.IntegerField(choices=[(0, 'Карзина'), (1, 'Самовоз'), (2, 'В процессе'), (3, 'На доставке'), (4, 'Отказ')], verbose_name='Статус')),
                ('order_id', models.IntegerField(verbose_name='ID заказ')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='piza.products', verbose_name='Продукт')),
            ],
        ),
    ]
