# Generated by Django 3.2 on 2022-10-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piza', '0039_auto_20221017_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=50, verbose_name='Статус')),
            ],
        ),
    ]
