# Generated by Django 3.2 on 2022-11-15 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piza', '0040_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='barnch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиал',
            },
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ['order_id'], 'verbose_name': 'Заказы', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RemoveField(
            model_name='deliveryinfo',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='status',
        ),
        migrations.AddField(
            model_name='deliveryinfo',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='InfoDelivery', to='piza.orders'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='order_id',
            field=models.IntegerField(default=1, verbose_name='Номер заказ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='paid',
            field=models.IntegerField(verbose_name='Цена'),
        ),
    ]
