# Generated by Django 3.2 on 2022-11-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piza', '0042_auto_20221115_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='time_preparing',
            field=models.IntegerField(blank=True, null=True, verbose_name='Время приготовления'),
        ),
    ]
