# Generated by Django 3.2 on 2022-11-17 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piza', '0043_products_time_preparing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='time_preparing',
            new_name='time',
        ),
    ]
