# Generated by Django 3.2 on 2022-11-17 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piza', '0044_rename_time_preparing_products_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='time',
            new_name='time_preparing',
        ),
    ]
