# Generated by Django 3.2 on 2022-11-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piza', '0045_rename_time_products_time_preparing'),
    ]

    operations = [
        migrations.CreateModel(
            name='slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=200, null=True, verbose_name='Картинка')),
                ('url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка')),
                ('status', models.IntegerField(choices=[(1, 'Отркыто'), (2, 'Закрыто')], verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайд',
            },
        ),
        migrations.AlterField(
            model_name='products',
            name='time_preparing',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Время приготовления'),
        ),
    ]
