# Generated by Django 3.2 on 2022-11-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piza', '0046_auto_20221118_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(default=1, upload_to='slide/%Y/%m/%d', verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
