# Generated by Django 3.2 on 2022-11-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piza', '0047_alter_slide_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='prioritet',
            field=models.IntegerField(default=1, verbose_name='Приоритет'),
            preserve_default=False,
        ),
    ]
