# Generated by Django 3.2 on 2022-11-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piza', '0052_auto_20221122_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_info',
            name='block',
            field=models.IntegerField(choices=[(0, 'Открыто'), (1, 'Блокирован')], default=0, verbose_name='Статус'),
        ),
    ]
