# Generated by Django 3.2 on 2022-11-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piza', '0053_contact_info_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryinfo',
            name='delivery_time',
            field=models.CharField(max_length=100, null=True, verbose_name='Время доставки'),
        ),
    ]
