# Generated by Django 3.2 on 2022-11-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piza', '0058_courier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='order_id',
            field=models.IntegerField(null=True, verbose_name='Номер заказа'),
        ),
    ]
