# Generated by Django 4.2 on 2023-05-20 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piza', '0062_alter_deliveryinfo_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryinfo',
            name='delivery_etime',
            field=models.DateTimeField(max_length=15, null=True, verbose_name='Время доставки'),
        ),
        migrations.AlterField(
            model_name='contact_info',
            name='block',
            field=models.IntegerField(choices=[(0, 'Открыто'), (1, 'Блокирован'), (2, 'Админ'), (99, 'Курьер')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='delivery_time',
            field=models.CharField(max_length=50, null=True, verbose_name='Срок доставки'),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='InfoDelivery', to='piza.orders'),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.IntegerField(choices=[(1, 'Пицца'), (2, 'Бургер'), (3, 'Стрипсы'), (4, 'Напитки'), (5, 'Соус'), (6, 'Картофель'), (7, 'Десерты'), (8, 'Роллы')], verbose_name='Категория'),
        ),
    ]
