# Generated by Django 4.2 on 2023-05-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piza', '0063_deliveryinfo_delivery_etime_alter_contact_info_block_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryinfo',
            name='delivery_etime',
            field=models.DateTimeField(max_length=15, verbose_name='Время доставки'),
        ),
    ]
