# Generated by Django 4.2 on 2023-05-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piza', '0064_alter_deliveryinfo_delivery_etime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryinfo',
            name='delivery_etime',
            field=models.DateTimeField(default=None, max_length=15, verbose_name='Время доставки'),
        ),
    ]
