# Generated by Django 4.2 on 2023-05-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piza', '0066_alter_deliveryinfo_delivery_etime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryinfo',
            name='delivery_etime',
            field=models.DateTimeField(max_length=15, verbose_name='Время доставки'),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='delivery_time',
            field=models.CharField(default='2999-12-31', max_length=50, verbose_name='Срок доставки'),
        ),
    ]
