# Generated by Django 4.2 on 2023-05-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piza', '0069_alter_deliveryinfo_delivery_etime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryinfo',
            name='delivery_etime',
            field=models.DateTimeField(null=True, verbose_name='Время доставки'),
        ),
    ]
